version: '3'
services:
  mariadb:
    image: 'mariadb:10.3.9'
    container_name: salary-mariadb
    ports:
        - '33062:3306'
    volumes:
        - ./docker/mysql-dump:/docker-entrypoint-initdb.d
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: demo_salary
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: salary-php-nginx
    volumes:
        - ./:/var/www/html
        - ./docker/nginx.conf:/etc/nginx/nginx.conf
    links:
        - 'mariadb:db'
    ports:
      - "81:80"