version: '3'
services:
  mariadb:
    image: 'mariadb:10.3.9'
    container_name: salary-mariadb
    ports:
        - '33062:3306'
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: demo_salary
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: salary-php-nginx
    volumes:
        - ./:/var/www/html
    links:
        - 'mariadb:db'
    ports:
      - "81:80"